# Generated by Django 5.2.14 on 2026-05-17 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('h3_index', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_type', models.CharField(max_length=100)),
                ('intersection_count', models.IntegerField(default=0)),
                ('region', models.CharField(default='lainnya', max_length=50)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('feasibility_prediction', models.CharField(default='LAYAK', max_length=50)),
                ('confidence_score', models.FloatField(default=87.0)),
                ('traffic_score_prediction', models.FloatField(default=0.0)),
                ('traffic_category_prediction', models.CharField(default='Low', max_length=50)),
                ('pdf_link', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.siteanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_count', models.IntegerField(default=0)),
                ('school_count', models.IntegerField(default=0)),
                ('bank_count', models.IntegerField(default=0)),
                ('hospital_count', models.IntegerField(default=0)),
                ('total_poi', models.IntegerField(default=0)),
                ('supermarket_count', models.IntegerField(default=0)),
                ('other_minimarket_count', models.IntegerField(default=0)),
                ('alfamidi_count', models.IntegerField(default=0)),
                ('total_competitor', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.siteanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisPopulation',
            fields=[
                ('population_id', models.AutoField(primary_key=True, serialize=False)),
                ('population_density', models.FloatField()),
                ('population_2020', models.IntegerField(default=0)),
                ('population_2026', models.IntegerField(default=0)),
                ('population_category', models.CharField(default='low', max_length=50)),
                ('data_source', models.CharField(default='WorldPop', max_length=100)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.siteanalysis')),
            ],
        ),
    ]
