# Generated by Django 5.2.14 on 2026-05-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_siteanalysis_nomor_dokumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteanalysis',
            name='nomor_dokumen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
