# Generated by Django 5.2.14 on 2026-06-07 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_siteanalysis_nomor_dokumen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysispopulation',
            options={'verbose_name': 'Analysis Population', 'verbose_name_plural': 'Analysis Populations'},
        ),
        migrations.AlterModelOptions(
            name='analysissnapshot',
            options={'verbose_name': 'Analysis Snapshot', 'verbose_name_plural': 'Analysis Snapshots'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='modelresult',
            options={'verbose_name': 'Model Result', 'verbose_name_plural': 'Model Results'},
        ),
        migrations.AlterModelOptions(
            name='siteanalysis',
            options={'ordering': ['-input_date'], 'verbose_name': 'Site Analysis', 'verbose_name_plural': 'Site Analyses'},
        ),
        migrations.AlterField(
            model_name='analysispopulation',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='dashboard.siteanalysis'),
        ),
        migrations.AlterField(
            model_name='analysissnapshot',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.siteanalysis'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.siteanalysis'),
        ),
        migrations.AlterField(
            model_name='siteanalysis',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_analyses', to='dashboard.location'),
        ),
        migrations.AlterField(
            model_name='siteanalysis',
            name='nomor_dokumen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
