# Generated by Django 6.0.6 on 2026-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_analysispopulation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='proposed_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
