# Generated by Django 6.0.7 on 2026-08-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_location_proposed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteanalysis',
            name='road_type',
            field=models.TextField(),
        ),
    ]
