# Generated by Django 5.2.16 on 2026-07-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_location_proposed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='h3_index',
        ),
    ]
