# Generated by Django 5.2.16 on 2026-08-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_siteanalysis_road_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='h3_index',
        ),
    ]
